import { GameMapType } from "./Maps.gen";

/** Runtime map identifiers for maps generated by the desktop application. */
export const CUSTOM_MAP_PREFIX = "custom:";

export interface CustomMapEntry {
  /** Folder name under the desktop application's user-data maps directory. */
  folder: string;
  name: string;
  width: number;
  height: number;
}

export interface CustomMapList {
  maps: CustomMapEntry[];
  /** HTTP origin serving the user-data map files. */
  assetBaseUrl: string | null;
}

/**
 * Includes the asset origin in the identifier because the Electron dev shell
 * and packaged shell can use different local HTTP ports. The identifier is
 * only used locally and is never sent to the multiplayer server.
 */
export function customMapValue(
  folder: string,
  assetBaseUrl: string,
): GameMapType {
  return `${CUSTOM_MAP_PREFIX}${encodeURIComponent(assetBaseUrl)}:${encodeURIComponent(folder)}` as GameMapType;
}

export function isCustomMap(map: unknown): map is GameMapType {
  return typeof map === "string" && map.startsWith(CUSTOM_MAP_PREFIX);
}

function customMapParts(map: string): [string, string] | null {
  if (!isCustomMap(map)) return null;
  const encoded = map.slice(CUSTOM_MAP_PREFIX.length);
  const separator = encoded.indexOf(":");
  if (separator < 0) {
    // Accept the short form for compatibility with any map value created by
    // an earlier renderer session.
    return ["", encoded];
  }
  return [encoded.slice(0, separator), encoded.slice(separator + 1)];
}

function decodePart(value: string): string {
  try {
    return decodeURIComponent(value);
  } catch {
    return value;
  }
}

export function customMapFolder(map: string): string | null {
  const parts = customMapParts(map);
  return parts ? decodePart(parts[1]) : null;
}

export function customMapAssetBaseUrl(map: string): string {
  const parts = customMapParts(map);
  if (!parts || !parts[0]) {
    return typeof location !== "undefined" ? location.origin : "";
  }
  return decodePart(parts[0]);
}

export function customMapAssetUrl(map: string, fileName: string): string {
  const folder = customMapFolder(map);
  if (folder === null) {
    throw new Error(`Not a custom map: ${map}`);
  }
  const baseUrl = customMapAssetBaseUrl(map).replace(/\/+$/, "");
  return `${baseUrl}/__custom-maps/${encodeURIComponent(folder)}/${fileName}`;
}
